name: 'Setup Firefox and geckodriver'
runs:
  using: "composite"
  steps:
    - run: |
        GECKODRIVER_URL=`curl -Ls -o /dev/null -w %{url_effective} https://github.com/mozilla/geckodriver/releases/latest`
        GECKODRIVER_VERSION=`echo $GECKODRIVER_URL | sed 's#.*/##'`
        export GECKODRIVER_DOWNLOAD="https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
        curl -L -o geckodriver.tar.gz $GECKODRIVER_DOWNLOAD
        gunzip -c geckodriver.tar.gz | tar xopf -
        chmod +x geckodriver && sudo mv geckodriver /usr/local/bin
        geckodriver --version
      shell: bash
